In [1]:
import pandas as pd
import numpy as np
import flask
import pymysql
import matplotlib.pyplot as plt
import seaborn as sns
import nltk

In [4]:
# Restaurent reviews prediction systems
# #Sentiment Analysis of Restaurant Reviews

In [5]:
# owner >> cust >> text >> model >> good or bad >> analysis 
# food >> quality inrease
# kaggle

In [ ]:
# problem statement

In [6]:
# Normally, a lot of businesses are remained as failures due to lack of profit, lack of proper 
# improvement measures. Mostly, restaurant owners face a lot of difficulties to improve their productivity. 
# This project really helps those who want to increase their productivity, which in turn increases 
# their business profits. This is the main objective of this project.

# What the project does is that the restaurant owner gets to know about drawbacks of 
# his restaurant such as most disliked food items of his restaurant by customer’s text 
# review which is processed with ML classification algorithm(Naive Bayes)

# The purpose of this analysis is to build a prediction model to predict whether 
# a review on the restaurant is positive or negative. To do so, we will work on Restaurant Review dataset, 
# we will load it into predicitve algorithms Multinomial Naive Bayes, Bernoulli Naive Bayes and 
# Logistic Regression. In the end, we hope to find a "best" model for predicting the review's sentiment.

In [7]:
# Dataset: Restaurant_Reviews.tsv is a dataset from Kaggle datasets which consists of 
# 1000 reviews on a restaurant.

# To build a model to predict if review is positive or negative, following steps are performed.

# Importing Dataset
# Preprocessing Dataset
# Vectorization
# Training and Classification
# Analysis Conclusion

In [9]:
# Tools & Technologies Used:
# NLTK
# Machine Learning
# Python
# Tkinter
# Mysql
# Pandas
# flask
# git and github

In [10]:
# step-1 Data collection

In [2]:
import pandas as pd
import numpy as np
import flask
import pymysql
import matplotlib.pyplot as plt
import seaborn as sns
import nltk

In [3]:
df=pd.read_csv('r_data.tsv',delimiter='\t')

In [4]:
df

                                                 Review  Liked
0                              Wow... Loved this place.      1
1                                    Crust is not good.      0
2             Not tasty and the texture was just nasty.      0
3     Stopped by during the late May bank holiday of...      1
4     The selection on the menu was great and so wer...      1
...                                                 ...    ...
1381                                              clean      1
1382                                               less      0
1383                                              clean      1
1384                                               less      0
1385                                              clean      1

[1386 rows x 2 columns]

In [5]:
df.shape

(1386, 2)

In [6]:
# step-2 Data cleaning

In [7]:
df.isnull().sum()

Review    0
Liked     0
dtype: int64

In [8]:
df.dtypes

Review      str
Liked     int64
dtype: object

In [9]:
# 1 >> positive /Good
# 0 >> negative /Bad

In [10]:
# step-3 EDA / Text preprocessing/ML preprocessing

# remove stopwords
# stemming
# lowercase

In [11]:
X=df['Review']
y=df['Liked']

In [12]:
y.value_counts()

Liked
1    792
0    594
Name: count, dtype: int64

In [13]:
# dataset is balanced

In [14]:
import nltk
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
from nltk.tokenize import word_tokenize
import re

In [15]:
# lowercase

text='Hi how are you'
newtext=text.lower()
print(newtext)

hi how are you

In [16]:
# remove digit or special characters

text='Hi ^&# how 123 are you?'


newresult=re.sub(r'[^a-zA-Z\s]','',text)
print(newresult)

Hi  how  are you

In [17]:
# tokenization >> break down sentence into words 

text='Hi how are you'
list1=word_tokenize(text)
print(list1)

['Hi', 'how', 'are', 'you']

In [18]:
# remove stopwords
# stopwords >> most comman words >> ex a an the on this ...

nltk.download('all')

[nltk_data] Downloading collection 'all'
[nltk_data]    |
[nltk_data]    | Downloading package abc to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package abc is already up-to-date!
[nltk_data]    | Downloading package alpino to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package alpino is already up-to-date!
[nltk_data]    | Downloading package averaged_perceptron_tagger to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package averaged_perceptron_tagger is already up-
[nltk_data]    |       to-date!
[nltk_data]    | Downloading package averaged_perceptron_tagger_eng to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package averaged_perceptron_tagger_eng is already
[nltk_data]    |       up-to-date!
[nltk_data]    | Downloading package averaged_perceptron_tagger_ru to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package averaged_perceptron_tagger_ru is already
[nltk_data]    |       up-to-date!
[nltk_data]    | Downloading package averaged_perceptron_tagger_rus to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package averaged_perceptron_tagger_rus is already
[nltk_data]    |       up-to-date!
[nltk_data]    | Downloading package basque_grammars to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package basque_grammars is already up-to-date!
[nltk_data]    | Downloading package bcp47 to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package bcp47 is already up-to-date!
[nltk_data]    | Downloading package biocreative_ppi to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package biocreative_ppi is already up-to-date!
[nltk_data]    | Downloading package bllip_wsj_no_aux to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package bllip_wsj_no_aux is already up-to-date!
[nltk_data]    | Downloading package book_grammars to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package book_grammars is already up-to-date!
[nltk_data]    | Downloading package brown to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package brown is already up-to-date!
[nltk_data]    | Downloading package brown_tei to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package brown_tei is already up-to-date!
[nltk_data]    | Downloading package cess_cat to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package cess_cat is already up-to-date!
[nltk_data]    | Downloading package cess_esp to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package cess_esp is already up-to-date!
[nltk_data]    | Downloading package chat80 to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package chat80 is already up-to-date!
[nltk_data]    | Downloading package city_database to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package city_database is already up-to-date!
[nltk_data]    | Downloading package cmudict to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package cmudict is already up-to-date!
[nltk_data]    | Downloading package comparative_sentences to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package comparative_sentences is already up-to-
[nltk_data]    |       date!
[nltk_data]    | Downloading package comtrans to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package comtrans is already up-to-date!
[nltk_data]    | Downloading package conll2000 to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package conll2000 is already up-to-date!
[nltk_data]    | Downloading package conll2002 to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package conll2002 is already up-to-date!
[nltk_data]    | Downloading package conll2007 to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package conll2007 is already up-to-date!
[nltk_data]    | Downloading package crubadan to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package crubadan is already up-to-date!
[nltk_data]    | Downloading package dependency_treebank to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package dependency_treebank is already up-to-date!
[nltk_data]    | Downloading package dolch to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package dolch is already up-to-date!
[nltk_data]    | Downloading package english_wordnet to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Unzipping corpora\english_wordnet.zip.
[nltk_data]    | Downloading package europarl_raw to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package europarl_raw is already up-to-date!
[nltk_data]    | Downloading package extended_omw to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package extended_omw is already up-to-date!
[nltk_data]    | Downloading package floresta to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package floresta is already up-to-date!
[nltk_data]    | Downloading package framenet_v15 to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package framenet_v15 is already up-to-date!
[nltk_data]    | Downloading package framenet_v17 to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package framenet_v17 is already up-to-date!
[nltk_data]    | Downloading package gazetteers to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package gazetteers is already up-to-date!
[nltk_data]    | Downloading package genesis to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package genesis is already up-to-date!
[nltk_data]    | Downloading package gutenberg to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package gutenberg is already up-to-date!
[nltk_data]    | Downloading package ieer to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package ieer is already up-to-date!
[nltk_data]    | Downloading package inaugural to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package inaugural is already up-to-date!
[nltk_data]    | Downloading package indian to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package indian is already up-to-date!
[nltk_data]    | Downloading package jeita to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package jeita is already up-to-date!
[nltk_data]    | Downloading package kimmo to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package kimmo is already up-to-date!
[nltk_data]    | Downloading package knbc to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package knbc is already up-to-date!
[nltk_data]    | Downloading package large_grammars to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package large_grammars is already up-to-date!
[nltk_data]    | Downloading package lin_thesaurus to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package lin_thesaurus is already up-to-date!
[nltk_data]    | Downloading package mac_morpho to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package mac_morpho is already up-to-date!
[nltk_data]    | Downloading package machado to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package machado is already up-to-date!
[nltk_data]    | Downloading package masc_tagged to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package masc_tagged is already up-to-date!
[nltk_data]    | Downloading package maxent_ne_chunker to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package maxent_ne_chunker is already up-to-date!
[nltk_data]    | Downloading package maxent_ne_chunker_tab to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package maxent_ne_chunker_tab is already up-to-
[nltk_data]    |       date!
[nltk_data]    | Downloading package maxent_treebank_pos_tagger to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package maxent_treebank_pos_tagger is already up-
[nltk_data]    |       to-date!
[nltk_data]    | Downloading package maxent_treebank_pos_tagger_tab to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package maxent_treebank_pos_tagger_tab is already
[nltk_data]    |       up-to-date!
[nltk_data]    | Downloading package mock_corpus to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package mock_corpus is already up-to-date!
[nltk_data]    | Downloading package moses_sample to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package moses_sample is already up-to-date!
[nltk_data]    | Downloading package movie_reviews to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package movie_reviews is already up-to-date!
[nltk_data]    | Downloading package mte_teip5 to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package mte_teip5 is already up-to-date!
[nltk_data]    | Downloading package mwa_ppdb to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package mwa_ppdb is already up-to-date!
[nltk_data]    | Downloading package names to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package names is already up-to-date!
[nltk_data]    | Downloading package nombank.1.0 to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package nombank.1.0 is already up-to-date!
[nltk_data]    | Downloading package nonbreaking_prefixes to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package nonbreaking_prefixes is already up-to-date!
[nltk_data]    | Downloading package nps_chat to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package nps_chat is already up-to-date!
[nltk_data]    | Downloading package omw to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package omw is already up-to-date!
[nltk_data]    | Downloading package omw-1.4 to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package omw-1.4 is already up-to-date!
[nltk_data]    | Downloading package opinion_lexicon to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package opinion_lexicon is already up-to-date!
[nltk_data]    | Downloading package panlex_swadesh to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package panlex_swadesh is already up-to-date!
[nltk_data]    | Downloading package paradigms to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package paradigms is already up-to-date!
[nltk_data]    | Downloading package pe08 to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package pe08 is already up-to-date!
[nltk_data]    | Downloading package perluniprops to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package perluniprops is already up-to-date!
[nltk_data]    | Downloading package pil to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package pil is already up-to-date!
[nltk_data]    | Downloading package pl196x to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package pl196x is already up-to-date!
[nltk_data]    | Downloading package porter_test to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package porter_test is already up-to-date!
[nltk_data]    | Downloading package ppattach to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package ppattach is already up-to-date!
[nltk_data]    | Downloading package problem_reports to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package problem_reports is already up-to-date!
[nltk_data]    | Downloading package product_reviews_1 to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package product_reviews_1 is already up-to-date!
[nltk_data]    | Downloading package product_reviews_2 to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package product_reviews_2 is already up-to-date!
[nltk_data]    | Downloading package propbank to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package propbank is already up-to-date!
[nltk_data]    | Downloading package pros_cons to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package pros_cons is already up-to-date!
[nltk_data]    | Downloading package ptb to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package ptb is already up-to-date!
[nltk_data]    | Downloading package punkt to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package punkt is already up-to-date!
[nltk_data]    | Downloading package punkt_tab to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package punkt_tab is already up-to-date!
[nltk_data]    | Downloading package qc to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package qc is already up-to-date!
[nltk_data]    | Downloading package reuters to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package reuters is already up-to-date!
[nltk_data]    | Downloading package rslp to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package rslp is already up-to-date!
[nltk_data]    | Downloading package rte to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package rte is already up-to-date!
[nltk_data]    | Downloading package sample_grammars to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package sample_grammars is already up-to-date!
[nltk_data]    | Downloading package semcor to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package semcor is already up-to-date!
[nltk_data]    | Downloading package senseval to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package senseval is already up-to-date!
[nltk_data]    | Downloading package sentence_polarity to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package sentence_polarity is already up-to-date!
[nltk_data]    | Downloading package sentiwordnet to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package sentiwordnet is already up-to-date!
[nltk_data]    | Downloading package shakespeare to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package shakespeare is already up-to-date!
[nltk_data]    | Downloading package sinica_treebank to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package sinica_treebank is already up-to-date!
[nltk_data]    | Downloading package smultron to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package smultron is already up-to-date!
[nltk_data]    | Downloading package snowball_data to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package snowball_data is already up-to-date!
[nltk_data]    | Downloading package spanish_grammars to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package spanish_grammars is already up-to-date!
[nltk_data]    | Downloading package state_union to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package state_union is already up-to-date!
[nltk_data]    | Downloading package stopwords to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package stopwords is already up-to-date!
[nltk_data]    | Downloading package subjectivity to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package subjectivity is already up-to-date!
[nltk_data]    | Downloading package swadesh to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package swadesh is already up-to-date!
[nltk_data]    | Downloading package switchboard to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package switchboard is already up-to-date!
[nltk_data]    | Downloading package tagsets to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package tagsets is already up-to-date!
[nltk_data]    | Downloading package tagsets_json to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package tagsets_json is already up-to-date!
[nltk_data]    | Downloading package timit to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package timit is already up-to-date!
[nltk_data]    | Downloading package toolbox to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package toolbox is already up-to-date!
[nltk_data]    | Downloading package treebank to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package treebank is already up-to-date!
[nltk_data]    | Downloading package twitter_samples to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package twitter_samples is already up-to-date!
[nltk_data]    | Downloading package udhr to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package udhr is already up-to-date!
[nltk_data]    | Downloading package udhr2 to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package udhr2 is already up-to-date!
[nltk_data]    | Downloading package unicode_samples to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package unicode_samples is already up-to-date!
[nltk_data]    | Downloading package universal_tagset to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package universal_tagset is already up-to-date!
[nltk_data]    | Downloading package universal_treebanks_v20 to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package universal_treebanks_v20 is already up-to-
[nltk_data]    |       date!
[nltk_data]    | Downloading package vader_lexicon to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package vader_lexicon is already up-to-date!
[nltk_data]    | Downloading package verbnet to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package verbnet is already up-to-date!
[nltk_data]    | Downloading package verbnet3 to

True

In [24]:
s_list=stopwords.words('english')

In [25]:
len(s_list)

198

In [26]:
text='cat sat on mat and this is real problem'
list1=word_tokenize(text)
print(list1)

['cat', 'sat', 'on', 'mat', 'and', 'this', 'is', 'real', 'problem']

In [27]:
list2=[  i for i in list1 if i not in s_list]

In [28]:
list2

['cat', 'sat', 'mat', 'real', 'problem']

In [29]:
# stemming /lemmatization
# to get root word 
# to cut off suffixes


# affect affecting affected >> affect

In [30]:
ps=PorterStemmer()
ps.stem('affected')

'affect'

In [31]:
# join

In [32]:
list1=['cat', 'sat', 'mat', 'real', 'problem']

In [33]:
finalstr=' '.join(list1)

In [34]:
finalstr

'cat sat mat real problem'

In [35]:
df['Review']

0                                Wow... Loved this place.
1                                      Crust is not good.
2               Not tasty and the texture was just nasty.
3       Stopped by during the late May bank holiday of...
4       The selection on the menu was great and so wer...
                              ...
1381                                                clean
1382                                                 less
1383                                                clean
1384                                                 less
1385                                                clean
Name: Review, Length: 1386, dtype: str

In [36]:
a='cat sat on mat'

In [37]:
a.split()

['cat', 'sat', 'on', 'mat']

In [38]:
import re

In [39]:
corpus=[]
for i in df['Review']:
    text=i.lower()
    text1=re.sub(r'[^a-zA-Z\s]','',text)
    list1=word_tokenize(text1)
    list2=[  i for i in list1 if i not in s_list]
    ps=PorterStemmer()
    list3=[  ps.stem(i) for i in list2]
    finalstr=' '.join(list3)
    corpus.append(finalstr)

In [41]:
corpus

['wow love place',
 'crust good',
 'tasti textur nasti',
 'stop late may bank holiday rick steve recommend love',
 'select menu great price',
 'get angri want damn pho',
 'honeslti didnt tast fresh',
 'potato like rubber could tell made ahead time kept warmer',
 'fri great',
 'great touch',
 'servic prompt',
 'would go back',
 'cashier care ever say still end wayyy overpr',
 'tri cape cod ravoli chicken cranberrymmmm',
 'disgust pretti sure human hair',
 'shock sign indic cash',
 'highli recommend',
 'waitress littl slow servic',
 'place worth time let alon vega',
 'like',
 'burritto blah',
 'food amaz',
 'servic also cute',
 'could care less interior beauti',
 'perform',
 'that rightth red velvet cakeohhh stuff good',
 'never brought salad ask',
 'hole wall great mexican street taco friendli staff',
 'took hour get food tabl restaur food luke warm sever run around like total overwhelm',
 'worst salmon sashimi',
 'also combo like burger fri beer decent deal',
 'like final blow',
 'found place accid could happier',
 'seem like good quick place grab bite familiar pub food favor look elsewher',
 'overal like place lot',
 'redeem qualiti restaur inexpens',
 'ampl portion good price',
 'poor servic waiter made feel like stupid everi time came tabl',
 'first visit hiro delight',
 'servic suck',
 'shrimp tender moist',
 'deal good enough would drag establish',
 'hard judg whether side good gross melt styrofoam didnt want eat fear get sick',
 'posit note server attent provid great servic',
 'frozen puck disgust worst peopl behind regist',
 'thing like prime rib dessert section',
 'bad food damn gener',
 'burger good beef cook right',
 'want sandwich go firehous',
 'side greek salad greek dress tasti pita hummu refresh',
 'order duck rare pink tender insid nice char outsid',
 'came run us realiz husband left sunglass tabl',
 'chow mein good',
 'horribl attitud toward custom talk one custom dont enjoy food',
 'portion huge',
 'love itfriendli server great food wonder imagin menu',
 'heart attack grill downtown vega absolut flatlin excus restaur',
 'much seafood like string pasta bottom',
 'salad right amount sauc power scallop perfectli cook',
 'rip banana rip petrifi tasteless',
 'least think refil water struggl wave minut',
 'place receiv star appet',
 'cocktail handmad delici',
 'wed definit go back',
 'glad found place',
 'great food servic huge portion give militari discount',
 'alway great time do gringo',
 'updatew back second time still amaz',
 'got food appar never heard salt batter fish chewi',
 'great way finish great',
 'deal includ tast drink jeff went beyond expect',
 'realli realli good rice time',
 'servic meh',
 'took min get milkshak noth chocol milk',
 'guess known place would suck insid excalibur didnt use common sens',
 'scallop dish quit appal valu well',
 'time bad custom servic',
 'sweet potato fri good season well',
 'today second time ive lunch buffet pretti good',
 'much good food vega feel cheat wast eat opportun go rice compani',
 'come like experienc underwhelm relationship parti cant wait person ask break',
 'walk place smell like old greas trap other eat',
 'turkey roast beef bland',
 'place',
 'pan cake everyon rave tast like sugari disast tailor palat six year old',
 'love pho spring roll oh yummi tri',
 'poor batter meat ratio made chicken tender unsatisfi',
 'say food amaz',
 'omelet die',
 'everyth fresh delici',
 'summari larg disappoint dine experi',
 'like realli sexi parti mouth your outrag flirt hottest person parti',
 'never hard rock casino never ever step forward',
 'best breakfast buffet',
 'say bye bye tip ladi',
 'well never go',
 'back',
 'food arriv quickli',
 'good',
 'side cafe serv realli good food',
 'server fantast found wife love roast garlic bone marrow ad extra meal anoth marrow go',
 'good thing waiter help kept bloddi mari come',
 'best buffet town price beat',
 'love mussel cook wine reduct duck tender potato dish delici',
 'one better buffet',
 'went tigerlilli fantast afternoon',
 'food delici bartend attent person got great deal',
 'ambienc wonder music play',
 'go back next trip',
 'sooooo good',
 'real sushi lover let honest yama good',
 'least min pass us order food arriv wasnt busi',
 'realli fantast thai restaur definit worth visit',
 'nice spici tender',
 'good price',
 'check',
 'pretti gross',
 'ive better atmospher',
 'kind hard mess steak',
 'although much like look sound place actual experi bit disappoint',
 'dont know place manag serv blandest food ever eaten prepar indian cuisin',
 'worst servic boot least worri',
 'servic fine waitress friendli',
 'guy steak steak love son steak best worst place said best steak he ever eaten',
 'thought youd ventur away get good sushi place realli hit spot night',
 'host staff lack better word bitch',
 'bland like place number reason dont want wast time bad review ill leav',
 'phenomen food servic ambianc',
 'wouldnt return',
 'definit worth ventur strip pork belli return next time im vega',
 'place way overpr mediocr food',
 'penn vodka excel',
 'good select food includ massiv meatloaf sandwich crispi chicken wrap delish tuna melt tasti burger',
 'manag rude',
 'delici nyc bagel good select cream chees real lox caper even',
 'great subway fact good come everi subway meet expect',
 'serious solid breakfast',
 'one best bar food vega',
 'extrem rude realli mani restaur would love dine weekend vega',
 'drink never empti made realli great menu suggest',
 'dont',
 'waiter wasnt help friendli rare check us',
 'husband ate lunch disappoint food servic',
 'red curri much bamboo shoot wasnt tasti',
 'nice blanket moz top feel like done cover subpar food',
 'bathroom clean place well decor',
 'menu alway chang food qualiti go servic extrem slow',
 'servic littl slow consid serv peopl server food come slow pace',
 'give thumb',
 'watch waiter pay lot attent tabl ignor us',
 'fianc came middl day greet seat right away',
 'great restaur mandalay bay',
 'wait forti five minut vain',
 'crostini came salad stale',
 'highlight great qualiti nigiri',
 'staff friendli joint alway clean',
 'differ cut piec day still wonder tender well well flavor',
 'order voodoo pasta first time id realli excel pasta sinc go gluten free sever year ago',
 'place good',
 'unfortun must hit bakeri leftov day everyth order stale',
 'came back today sinc reloc still impress',
 'seat immedi',
 'menu divers reason price',
 'avoid cost',
 'restaur alway full never wait',
 'delici',
 'place handsdown one best place eat phoenix metro area',
 'dont go look good food',
 'ive never treat bad',
 'bacon hella salti',
 'also order spinach avocado salad ingredi sad dress liter zero tast',
 'realli vega fine dine use right menu hand ladi price list',
 'waitress friendli',
 'lordi khao soi dish miss curri lover',
 'everyth menu terrif also thrill made amaz accommod vegetarian daughter',
 'perhap caught night judg review im inspir go back',
 'servic leav lot desir',
 'atmospher modern hip maintain touch cozi',
 'weekli haunt definit place come back everi',
 'liter sat minut one ask take order',
 'burger absolut flavor meat total bland burger overcook charcoal flavor',
 'also decid send back waitress look like verg heart attack',
 'dress treat rude',
 'probabl dirt',
 'love place hit spot want someth healthi lack quantiti flavor',
 'order lemon raspberri ice cocktail also incred',
 'food suck expect suck could imagin',
 'interest decor',
 'realli like crepe station',
 'also serv hot bread butter home made potato chip bacon bit topveri origin good',
 'watch prepar delici food',
 'egg roll fantast',
 'order arriv one gyro miss',
 'salad wing ice cream dessert left feel quit satisfi',
 'im realli sure joey vote best hot dog valley reader phoenix magazin',
 'best place go tasti bowl pho',
 'live music friday total blow',
 'ive never insult felt disrespect',
 'friendli staff',
 'worth drive',
 'heard good thing place exceed everi hope could dream',
 'food great serivc',
 'warm beer didnt help',
 'great brunch spot',
 'servic friendli invit',
 'good lunch spot',
 'ive live sinc first last time ive step foot place',
 'worst experi ever',
 'must night place',
 'side delish mix mushroom yukon gold pure white corn beateou',
 'bug never show would given sure side wall bug climb kitchen',
 'minut wait salad realiz wasnt come time soon',
 'friend love salmon tartar',
 'wont go back',
 'extrem tasti',
 'waitress good though',
 'soggi good',
 'jamaican mojito delici',
 'small worth price',
 'food rich order accordingli',
 'shower area outsid rins take full shower unless dont mind nude everyon see',
 'servic bit lack',
 'lobster bisqu bussel sprout risotto filet need salt pepperand cours none tabl',
 'hope bode go busi someon cook come',
 'either cold enough flavor bad',
 'love bacon wrap date',
 'unbeliev bargain',
 'folk otto alway make us feel welcom special',
 'main also uninspir',
 'place first pho amaz',
 'wonder experi made place muststop whenev town',
 'food isnt bad enough enjoy deal world worstannoy drunk peopl',
 'fun chef',
 'order doubl cheeseburg got singl patti fall apart pictur upload yeah still suck',
 'great place coupl drink watch sport event wall cover tv',
 'possibl give zero star theyd',
 'descript said yum yum sauc anoth said eel sauc yet anoth said spici mayowel none roll sauc',
 'id say would hardest decis honestli ms dish tast suppos tast amaz',
 'roll eye may stay sure go back tri',
 'everyon attent provid excel custom servic',
 'horribl dont wast time money',
 'dish quit flavour',
 'time side restaur almost empti excus',
 'wasnt busi either also build freez cold',
 'like review said couldnt pay eat place',
 'drink took close minut come one point',
 'serious flavor delight folk',
 'much better ayc sushi place went vega',
 'light dark enough set mood',
 'base subpar servic receiv effort show gratitud busi wont go back',
 'owner realli great peopl',
 'noth privileg working',
 'greek dress creami flavor',
 'overal dont think would take parent place made similar complaint silent felt',
 'pizza good peanut sauc tasti',
 'tabl servic pretti fast',
 'fantast servic',
 'well wouldv given godfath zero star possibl',
 'know make',
 'tough short flavor',
 'hope place stick around',
 'bar vega ever recal charg tap water',
 'restaur atmospher exquisit',
 'good servic clean inexpens boot',
 'seafood fresh gener portion',
 'plu buck',
 'servic par either',
 'thu far visit twice food absolut delici time',
 'good year ago',
 'self proclaim coffe cafe wildli disappoint',
 'veggitarian platter world',
 'cant go wrong food',
 'cant beat',
 'stop place madison ironman friendli kind staff',
 'chef friendli good job',
 'ive better dedic boba tea spot even jenni pho',
 'like patio servic outstand',
 'goat taco didnt skimp meat wow flavor',
 'think',
 'mac salad pretti bland get',
 'went bachi burger friend recommend disappoint',
 'servic stink',
 'wait wait',
 'place qualiti sushi qualiti restaur',
 'would definit recommend wing well pizza',
 'great pizza salad',
 'thing went wrong burn saganaki',
 'wait hour breakfast could done time better home',
 'place amaz',
 'hate disagre fellow yelper husband disappoint place',
 'wait hour never got either pizza mani around us came later',
 'dont know slow',
 'staff great food delish incred beer select',
 'live neighborhood disappoint wont back conveni locat',
 'didnt know pull pork could soooo delici',
 'get incred fresh fish prepar care',
 'go gave star rate pleas know third time eat bachi burger write review',
 'love fact everyth menu worth',
 'never dine place',
 'food excel servic good',
 'good beer drink select good food select',
 'pleas stay away shrimp stir fri noodl',
 'potato chip order sad could probabl count mani chip box probabl around',
 'food realli bore',
 'good servicecheck',
 'greedi corpor never see anoth dime',
 'never ever go back',
 'much id like go back cant get pass atroci servic never return',
 'summer dine charm outdoor patio delight',
 'expect good',
 'fantast food',
 'order toast english muffin came untoast',
 'food good',
 'never go back',
 'great food price high qualiti hous made',
 'bu boy hand rude',
 'point friend basic figur place joke didnt mind make publicli loudli known',
 'back good bbq lighter fare reason price tell public back old way',
 'consid two us left full happi cant go wrong',
 'bread made inhous',
 'downsid servic',
 'also fri without doubt worst fri ive ever',
 'servic except food good review',
 'coupl month later return amaz meal',
 'favorit place town shawarrrrrrma',
 'black eye pea sweet potato unreal',
 'wont disappoint',
 'could serv vinaigrett may make better overal dish still good',
 'go far mani place ive never seen restaur serv egg breakfast especi',
 'mom got home immedi got sick bite salad',
 'server pleasant deal dont alway honor pizza hut coupon',
 'truli unbeliev good glad went back',
 'fantast servic pleas atmospher',
 'everyth gross',
 'love place',
 'great servic food',
 'first bathroom locat dirti seat cover replenish plain yucki',
 'burger got gold standard burger kind disappoint',
 'omg food delicioso',
 'noth authent place',
 'spaghetti noth special whatsoev',
 'dish salmon best great',
 'veget fresh sauc feel like authent thai',
 'worth drive tucson',
 'select probabl worst ive seen vegasther none',
 'pretti good beer select',
 'place like chipotl better',
 'classywarm atmospher fun fresh appet succul steak basebal steak',
 'star brick oven bread app',
 'eaten multipl time time food delici',
 'sat anoth ten minut final gave left',
 'terribl',
 'everyon treat equal special',
 'shouldnt take min pancak egg',
 'delici',
 'good side staff genuin pleasant enthusiast real treat',
 'sadli gordon ramsey steak place shall sharpli avoid next trip vega',
 'alway even wonder food delici',
 'best fish ive ever life',
 'bathroom next door nice',
 'buffet small food offer bland',
 'outstand littl restaur best food ever tast',
 'pretti cool would say',
 'definit turn doubt ill back unless someon els buy',
 'server great job handl larg rowdi tabl',
 'find wast food despic wasnt food',
 'wife lobster bisqu soup lukewarm',
 'would come back sushi crave vega',
 'staff great ambianc great',
 'deserv star',
 'left stomach ach felt sick rest day',
 'drop ball',
 'dine space tini elegantli decor comfort',
 'custom order way youd like usual eggplant green bean stir fri love',
 'bean rice mediocr best',
 'best taco town far',
 'took back money got outta',
 'interest part town place amaz',
 'rude inconsider manag',
 'staff friendli wait time serv horribl one even say hi first minut',
 'wont back',
 'great dinner',
 'servic outshin definit recommend halibut',
 'food terribl',
 'never ever go back told mani peopl happen',
 'dont recommend unless car break front starv',
 'come back everi time im vega',
 'place deserv one star food',
 'disgrac',
 'def come back bowl next time',
 'want healthi authent ethic food tri place',
 'continu come ladi night andddd date night highli recommend place anyon area',
 'sever time past experi alway great',
 'walk away stuf happi first vega buffet experi',
 'servic excel price pretti reason consid vega locat insid crystal shop mall aria',
 'summar food incred nay transcend noth bring joy quit like memori pneumat condiment dispens',
 'im probabl one peopl ever go ian like',
 'kid pizza alway hit lot great side dish option kiddo',
 'servic perfect famili atmospher nice see',
 'cook perfect servic impecc',
 'one simpli disappoint',
 'overal disappoint qualiti food bouchon',
 'dont account know im get screw',
 'great place eat remind littl mom pop shop san francisco bay area',
 'today first tast buldogi gourmet hot dog tell ever thought possibl',
 'left frustrat',
 'ill definit soon',
 'food realli good got full petti fast',
 'servic fantast',
 'total wast time',
 'dont know kind best ice tea',
 'come hungri leav happi stuf',
 'servic give star',
 'assur wont disappoint',
 'take littl bad servic food suck',
 'gave tri eat crust teeth still sore',
 'complet gross',
 'realli enjoy eat',
 'first time go think quickli becom regular',
 'server nice even though look littl overwhelm need stay profession friendli end',
 'dinner companion told meeveryth fresh nice textur tast',
 'ground right next tabl larg smear beensteppedinandtrackedeverywher pile green bird poop',
 'furthermor cant even find hour oper websit',
 'weve tri like place time think done',
 'mistak',
 'complaint',
 'serious good pizza im expertconnisseur topic',
 'waiter jerk',
 'strike want rush',
 'nicest restaur owner ive ever come across',
 'never come',
 'love biscuit',
 'servic quick friendli',
 'order appet took minut pizza anoth minut',
 'absolutley fantast',
 'huge awkward lb piec cow th gristl fat',
 'definit come back',
 'like steiner dark feel like bar',
 'wow spici delici',
 'your familiar check',
 'ill take busi dinner dollar elsewher',
 'id love go back',
 'anyway fs restaur wonder breakfastlunch',
 'noth special',
 'day week differ deal delici',
 'mention combin pear almond bacon big winner',
 'back',
 'sauc tasteless',
 'food delici spici enough sure ask spicier prefer way',
 'ribey steak cook perfectli great mesquit flavor',
 'dont think well go back anytim soon',
 'food gooodd',
 'far sushi connoisseur definit tell differ good food bad food certainli bad food',
 'insult',
 'last time lunch bad',
 'chicken wing contain driest chicken meat ever eaten',
 'food good enjoy everi mouth enjoy relax venu coupl small famili group etc',
 'nargil think great',
 'best tater tot southwest',
 'love place',
 'definit worth paid',
 'vanilla ice cream creami smooth profiterol choux pastri fresh enough',
 'im az time new spot',
 'manag worst',
 'insid realli quit nice clean',
 'food outstand price reason',
 'dont think ill run back carli anytim soon food',
 'due fact took minut acknowledg anoth minut get foodand kept forget thing',
 'love margarita',
 'first vega buffet disappoint',
 'good though',
 'one note ventil could use upgrad',
 'great pork sandwich',
 'dont wast time',
 'total letdown would much rather go camelback flower shop cartel coffe',
 'third chees friend burger cold',
 'enjoy pizza brunch',
 'steak well trim also perfectli cook',
 'group claim would handl us beauti',
 'love',
 'ask bill leav without eat didnt bring either',
 'place jewel la vega exactli ive hope find nearli ten year live',
 'seafood limit boil shrimp crab leg crab leg definit tast fresh',
 'select food best',
 'delici absolut back',
 'isnt small famili restaur fine dine establish',
 'toro tartar cavier extraordinari like thinli slice wagyu white truffl',
 'dont think back long time',
 'attach ga station rare good sign',
 'awesom',
 'back mani time soon',
 'menu much good stuff could decid',
 'wors humili worker right front mebunch horribl name call',
 'conclus fill meal',
 'daili special alway hit group',
 'tragedi struck',
 'pancak also realli good pretti larg',
 'first crawfish experi delici',
 'monster chicken fri steak egg time favorit',
 'waitress sweet funni',
 'also tast mom multigrain pumpkin pancak pecan butter amaz fluffi delici',
 'id rather eat airlin food serious',
 'cant say enough good thing place',
 'ambianc incred',
 'waitress manag friendli',
 'would recommend place',
 'overal wasnt impress noca',
 'gyro basic lettuc',
 'terribl servic',
 'thoroughli disappoint',
 'dont much pasta love homemad hand made pasta thin pizza',
 'give tri happi',
 'far best cheesecurd ever',
 'reason price also',
 'everyth perfect night',
 'food good typic bar food',
 'drive get',
 'first glanc love bakeri cafe nice ambianc clean friendli staff',
 'anyway think go back',
 'point finger item menu order wont disappoint',
 'oh thing beauti restaur',
 'havent gone go',
 'greasi unhealthi meal',
 'first time might last',
 'burger amaz',
 'similarli deliveri man say word apolog food minut late',
 'way expens',
 'sure order dessert even need pack togo tiramisu cannoli die',
 'first time cant wait next',
 'bartend also nice',

In [54]:
# vectorization 
# text data to numeric form
# countvectoizer

In [42]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer()
X=cv.fit_transform(corpus).toarray()
y=df['Liked']

In [43]:
X.shape

(1386, 1611)

In [44]:
df.shape

(1386, 2)

In [45]:
cv.get_feature_names_out()

array(['absolut', 'absolutley', 'accid', ..., 'yum', 'yummi', 'zero'],
      shape=(1611,), dtype=object)

In [46]:
X_df=pd.DataFrame(X,columns=cv.get_feature_names_out())

In [47]:
X_df

,absolut,absolutley,accid,accommod,accomod,accordingli,account,ach,acknowledg,across,...,yelper,yet,youd,youll,your,yucki,yukon,yum,yummi,zero
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1381,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1382,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1383,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1384,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1385,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [48]:
# train test split >> cross validation

In [49]:
# model training >> Logistic Regression ,Multinomial ,Bernoullies

In [50]:
# Training and Classification
# Further the data is splitted into training and testing set using Cross Validation technique. 
# This data is used as input to classification algorithm.

# Classification Algorithms:

# Algorithms like Decision tree, Support Vector Machine, Logistic Regression, 
# Naive Bayes were implemented and on comparing the evaluation metrics two of the algorithms 
# gave better predictions than others.

# Multinomial Naive Bayes
# Bernoulli Naive Bayes
# Logistic Regression

In [51]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X_df,y,test_size=0.2,random_state=42)

In [52]:
#Multinomial NB

In [53]:
from sklearn.naive_bayes import MultinomialNB
classifier1= MultinomialNB()
classifier1.fit(X_train, y_train)

y_pred = classifier1.predict(X_test)

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print ("Confusion Matrix:\n",cm)

# Accuracy, Precision and Recall
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import classification_report
print('Classification Report\n', classification_report(y_test, y_pred))
score1 = accuracy_score(y_test,y_pred)
score2 = precision_score(y_test,y_pred)
score3= recall_score(y_test,y_pred)
print("\n")
print("Accuracy is ",round(score1*100,2),"%")
print("Precision is ",round(score2,2))
print("Recall is ",round(score3,2))

Confusion Matrix:
 [[ 87  33]
 [ 23 135]]
Classification Report
               precision    recall  f1-score   support

           0       0.79      0.72      0.76       120
           1       0.80      0.85      0.83       158

    accuracy                           0.80       278
   macro avg       0.80      0.79      0.79       278
weighted avg       0.80      0.80      0.80       278



Accuracy is  79.86 %
Precision is  0.8
Recall is  0.85

In [54]:
from sklearn.naive_bayes import BernoulliNB
classifier2= BernoulliNB()
classifier2.fit(X_train, y_train)

y_pred = classifier2.predict(X_test)

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print ("Confusion Matrix:\n",cm)

# Accuracy, Precision and Recall
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import classification_report
print('Classification Report\n', classification_report(y_test, y_pred))
score1 = accuracy_score(y_test,y_pred)
score2 = precision_score(y_test,y_pred)
score3= recall_score(y_test,y_pred)
print("\n")
print("Accuracy is ",round(score1*100,2),"%")
print("Precision is ",round(score2,2))
print("Recall is ",round(score3,2))

Confusion Matrix:
 [[ 78  42]
 [ 20 138]]
Classification Report
               precision    recall  f1-score   support

           0       0.80      0.65      0.72       120
           1       0.77      0.87      0.82       158

    accuracy                           0.78       278
   macro avg       0.78      0.76      0.77       278
weighted avg       0.78      0.78      0.77       278



Accuracy is  77.7 %
Precision is  0.77
Recall is  0.87

In [55]:
from sklearn.linear_model import LogisticRegression
classifier3= LogisticRegression()
classifier3.fit(X_train, y_train)

y_pred = classifier3.predict(X_test)

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print ("Confusion Matrix:\n",cm)

# Accuracy, Precision and Recall
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import classification_report
print('Classification Report\n', classification_report(y_test, y_pred))
score1 = accuracy_score(y_test,y_pred)
score2 = precision_score(y_test,y_pred)
score3= recall_score(y_test,y_pred)
print("\n")
print("Accuracy is ",round(score1*100,2),"%")
print("Precision is ",round(score2,2))
print("Recall is ",round(score3,2))

Confusion Matrix:
 [[ 96  24]
 [ 28 130]]
Classification Report
               precision    recall  f1-score   support

           0       0.77      0.80      0.79       120
           1       0.84      0.82      0.83       158

    accuracy                           0.81       278
   macro avg       0.81      0.81      0.81       278
weighted avg       0.81      0.81      0.81       278



Accuracy is  81.29 %
Precision is  0.84
Recall is  0.82

In [56]:
# Logistic regression >> 81.29%
# BernoulliNB >> 78%
# MultinomialNB >> 80%

In [57]:
# #Analysis and Conclusion

In [58]:
# In this study, an attempt has been made to classify sentiment analysis for restaurant reviews 
# using machine learning techniques. Two algorithms namely Multinomial Naive Bayes and 
# Bernoulli Naive Bayes are implemented.

# Evaluation metrics used here are accuracy, precision and recall.


# Using Multinomial Naive Bayes,
# Accuracy is  79.86 %
# Precision is  0.8
# Recall is  0.85


# Using Bernoulli Naive Bayes,
# Accuracy is  77.7 %
# Precision is  0.77
# Recall is  0.87


# Using Logistic Regression,
# Accuracy is  81.29 %
# Precision is  0.84
# Recall is  0.82


# From the above results, Logistic Regression is slightly better than Multinomial Naive Bayes

In [59]:
# final model >> Logistic regression

In [60]:
from sklearn.linear_model import LogisticRegression
classifier3= LogisticRegression()
classifier3.fit(X_df, y)

LogisticRegression()

In [61]:
import pickle

In [62]:
with open('lgmodel','wb') as f:
    pickle.dump(classifier3,f)

In [63]:
with open('cvmodel','wb') as f:
    pickle.dump(cv,f)

In [64]:
# new text prediction

In [92]:
a='not good taste'

In [93]:
newpredlist=[a]

In [94]:
a_cv=cv.transform(newpredlist).toarray()

In [95]:
a_cv

array([[0, 0, 0, ..., 0, 0, 0]], shape=(1, 1611))

In [96]:
a_cv.shape

(1, 1611)

In [97]:
result=classifier3.predict(a_cv)

d:\WE_project\rest_ml_project\venv314\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

In [98]:
result[0]

np.int64(1)

In [99]:
if 'not' in a.lower():
    result=abs(result[0]-1)
else:
    result=result[0]

In [100]:
result

np.int64(0)